name: MineGoEconomy
author: Gregoire Alperovitcj
version: v1.0
api: null

main: fr.minego.economy.Economy

commands:
  money:
    description: Permet les interactions avec la monnaie
    permission: economy.give
  balance:
    description: Permet de voir son nombre de monnaie
    permission: economy.balance